"""AI strategy code generator."""

import anthropic
import re
from typing import Optional, List, Tuple


STRATEGY_TEMPLATE = '''
"""
{strategy_name}
Generated by AutoStrategy

Hypothesis: {hypothesis}
"""

import pandas as pd
import numpy as np
from typing import Tuple, List


def compute_signals(prices: pd.DataFrame, volumes: pd.DataFrame) -> pd.Series:
    """
    Compute trading signals.
    
    Args:
        prices: DataFrame with columns as tickers, index as dates
        volumes: DataFrame with same structure
        
    Returns:
        Series of signals: 1 (long), 0 (flat), -1 (short)
    """
    {signal_logic}
    

def position_size(signal: int, volatility: float, capital: float) -> float:
    """Calculate position size based on signal and volatility."""
    if signal == 0:
        return 0
    base_size = capital * 0.1  # 10% per position
    vol_adjusted = base_size / max(volatility, 0.01)
    return min(vol_adjusted, capital * 0.25)  # Max 25% per position


def entry_condition(prices: pd.DataFrame, idx: int) -> bool:
    """Check if entry conditions are met."""
    {entry_logic}


def exit_condition(prices: pd.DataFrame, idx: int, entry_price: float) -> bool:
    """Check if exit conditions are met."""
    {exit_logic}
'''


class StrategyCoder:
    """Generate trading strategy code from hypotheses."""
    
    def __init__(self, llm_config: dict):
        self.client = anthropic.Anthropic()
        self.model = llm_config.get("model", "claude-sonnet-4-20250514")
        
    def generate(
        self,
        hypothesis: str,
        previous_strategy: Optional[str] = None,
        lessons: Optional[List[str]] = None
    ) -> Tuple[str, str]:
        """
        Generate strategy code from hypothesis.
        
        Returns:
            (code, strategy_name)
        """
        lessons_text = ""
        if lessons:
            lessons_text = "Lessons learned from previous attempts:\n" + "\n".join(f"- {l}" for l in lessons)
        
        evolution_text = ""
        if previous_strategy:
            evolution_text = f"Previous strategy to evolve:\n```python\n{previous_strategy}\n```\n\nImprove upon this strategy."
        
        prompt = f"""You are an expert quantitative trader. Generate a trading strategy based on this hypothesis:

HYPOTHESIS: {hypothesis}

{lessons_text}

{evolution_text}

Generate a complete Python trading strategy with:
1. Signal computation (momentum, mean reversion, etc.)
2. Entry conditions  
3. Exit conditions (including stop-loss and take-profit)

IMPORTANT DATA FORMAT:
- prices: DataFrame where COLUMNS are ticker symbols (e.g., 'SPY', 'QQQ', 'AAPL') and values are CLOSE prices
- volumes: DataFrame with same structure, values are Volume
- Example: prices['SPY'] returns a Series of SPY close prices
- DO NOT use prices['close'] or prices['open'] - those columns don't exist!

Output ONLY the Python code, no explanations. Use this exact structure:

```python
\"\"\"
strategy_name: <descriptive_snake_case_name>
\"\"\"

import pandas as pd
import numpy as np

def compute_signals(prices: pd.DataFrame, volumes: pd.DataFrame) -> pd.Series:
    \"\"\"
    Compute trading signals for each ticker.
    
    Args:
        prices: DataFrame with ticker columns (SPY, QQQ, etc.), values are close prices
        volumes: DataFrame with ticker columns, values are volume
        
    Returns:
        Series indexed by ticker symbols with signal values: 1 (long), 0 (flat), -1 (short)
    \"\"\"
    signals = pd.Series(0, index=prices.columns)
    
    for ticker in prices.columns:
        close = prices[ticker]
        volume = volumes[ticker]
        # Your logic here - compute signal for this ticker
        # signals[ticker] = 1, 0, or -1
    
    return signals

def entry_condition(prices: pd.DataFrame, idx: int) -> bool:
    \"\"\"Check if entry conditions are met. prices has single ticker column.\"\"\"
    ticker = prices.columns[0]
    close = prices[ticker]
    # Your entry logic using close.iloc[idx], close.iloc[idx-1], etc.
    return True  # or False

def exit_condition(prices: pd.DataFrame, idx: int, entry_price: float, current_price: float) -> bool:
    \"\"\"Check if exit conditions are met. Includes stop-loss and take-profit.\"\"\"
    # Stop loss at 5%
    if current_price < entry_price * 0.95:
        return True
    # Take profit at 10%
    if current_price > entry_price * 1.10:
        return True
    # Your additional exit logic
    return False
```
"""

        response = self.client.messages.create(
            model=self.model,
            max_tokens=2000,
            messages=[{"role": "user", "content": prompt}]
        )
        
        code = self._extract_code(response.content[0].text)
        name = self._extract_name(code)
        
        return code, name
    
    def generate_new_hypothesis(self, lessons: List[str]) -> str:
        """Generate a new hypothesis based on lessons learned."""
        lessons_text = "\n".join(f"- {l}" for l in lessons) if lessons else "No previous lessons."
        
        prompt = f"""You are an expert quantitative trader. Based on these lessons from previous strategy attempts:

{lessons_text}

Generate ONE new trading hypothesis to test. Be specific and actionable.
Examples:
- "Momentum strategies work better with volume confirmation above 1.5x average"
- "Mean reversion on RSI < 30 works for large-cap tech stocks"
- "Breakout strategies need ATR-based stops to avoid whipsaws"

Output ONLY the hypothesis, one line, no explanation."""

        response = self.client.messages.create(
            model=self.model,
            max_tokens=200,
            messages=[{"role": "user", "content": prompt}]
        )
        
        return response.content[0].text.strip()
    
    def _extract_code(self, text: str) -> str:
        """Extract Python code from response."""
        # Try to find code block
        match = re.search(r'```python\n(.*?)```', text, re.DOTALL)
        if match:
            return match.group(1).strip()
        # Fallback: assume entire response is code
        return text.strip()
    
    def _extract_name(self, code: str) -> str:
        """Extract strategy name from code."""
        match = re.search(r'strategy_name:\s*(\w+)', code)
        if match:
            return match.group(1)
        # Generate a default name
        import hashlib
        hash_suffix = hashlib.md5(code.encode()).hexdigest()[:6]
        return f"strategy_{hash_suffix}"
